- name: Run latest-tag
  uses: EndBug/latest-tag@latest
  with:
    # You can change the name of the tag with this input.
    # Default: 'latest'
    tag-name: someCustomTagName

    # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
    # Optional
    description: Description for the tag
